# === === === Base Properties === === ===
modId=ovo
modName=OVO
modVersion=2.0.0
modGroupId=club.someoneice.ovo
modArchivesName=OVO
modDescription=Make your idea come true, with json.

# === === === Kotlin Properties === === ===
kotlin_version=2.3.20

# === === === Pineapple Club Version === === ===
psychic_version=1.+
tags_version=1.+
recipe_book_version=1.0
wolftailui_version=0.0.4-BETA-1


nei_version=2.5.17
cc_version=1.2.1
